# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Larry
tagline:             'A STL-like container & algorithms library for C++11'
description:         ''
url:                 http://dezelin.github.io/larry/
baseurl:             /larry/
paginate:            5

# About/contact
author:
  name:              Aleksandar Dezelin
  url:               
  email:             dezelin@gmail.com

# Custom vars
version:             0.0.1
