# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Larry
tagline:             'A STL-like container & algorithms library for C++11'
description:         ''
url:                 https://dezelin.github.io/larry/
baseurl:             https://dezelin.github.io/larry
paginate:            5

# About/contact
author:
  name:              Aleksandar Dezelin
  url:               
  email:             dezelin@gmail.com

# Custom vars
version:             0.0.1
github:
    repo:            https://github.com/dezelin/larry

